repos:
  - repo: local
    hooks:
      - id: lint-research-docs
        name: Lint research docs for mid-word splits
        entry: python scripts/lint_research_docs.py
        language: system
        types: [markdown]
        files: ^docs/ai-research/.*\.md$
      - id: update-ai-research-index
        name: Update ai-research index
        entry: python scripts/update_ai_research_index.py
        language: system
        pass_filenames: false
        files: ^docs/ai-research/.*\.md$
