name: Build & Deploy Docs
on:
  push:
    paths: ["**.md", "**.pdf", "mkdocs.yml"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install mkdocs-material mkdocs-monorepo-plugin
      - run: mkdocs gh-deploy --force
